services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=travel_requests
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - MAIL_HOST=mailpit
    depends_on:
      - mysql
      - mailpit
    networks:
      - travel-network

  mysql:
    image: mysql:8.0
    container_name: travel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: travel_requests
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - travel-network

  mailpit:
    image: axllent/mailpit
    container_name: travel_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

volumes:
  mysql_data:
